# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Y2Q2NDM2YmRhNGQ0OTk1MTkzMmRkMjg3ODI5YmYwNTU2ZGEzNWFhNWRiNWE1OTUzODkzNjJlNzlkN2MzYTNiYWNhZGNhNjA1MjJkOGM1NjBlOWY0OTkyNWU3MGQ1N2I1MzJkNTEzODU5ODE0Y2ZhYjA5Yzc3ODI3MjMxYjgzZTE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
